-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."encounter_rat_constraints" add column "external_contract" text
--  null;
